/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiComponents;

import Utils.ArithmeticResultGenerator.ArithmeticResultGenerator;
import Utils.ArithmeticResultGenerator.DBSRG;
import Utils.ArithmeticResultGenerator.OTARG;
import Utils.GUIHandler;
import java.sql.SQLException;
import java.util.List;
import java.util.Objects;

/**
 *
 * @author joako
 */
public class ArithmeticDisplayer extends javax.swing.JFrame {
    private GUIHandler guihandler;
    /**
     * Creates new form ArithmeticDisplayer
     */
    public ArithmeticDisplayer() {
        initComponents();
    }
    
    public void display(List <Objects> atributes, ArithmeticResultGenerator arithmeticResultGenerator){
        this.removeAll();
        List<Object> atr;
        atr=null;
        try{
        atr = arithmeticResultGenerator.generateResults();}
        catch(SQLException e){}
        if(arithmeticResultGenerator instanceof DBSRG){
            this.add(this.dbaddedPanel);
            amountOfPeopleResult.setText((String)atr.get(0));
            amountOfCuadrantsResult.setText((String)atr.get(1));
            amountOfObjectsResult.setText((String)atr.get(2));
            amountOfBoxesResult.setText((String)atr.get(3));
        }else if(arithmeticResultGenerator instanceof OTARG){
            this.add(this.amountObjectsPanel);
            ceramicObjectsResult.setText((String)atr.get(0));
            lithicObjectsResult.setText((String)atr.get(1));
        }else{
            this.add(this.statisticsPanel);
            averageResult.setText((String)atr.get(0));
            minResult.setText((String)atr.get(1));
            maxResult.setText((String)atr.get(2));
        }
        this.repaint();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dbaddedPanel = new javax.swing.JPanel();
        amountOfPeopleT = new javax.swing.JLabel();
        amountOfCuadrantT = new javax.swing.JLabel();
        amountOfObjectsT = new javax.swing.JLabel();
        amountOfBoxesT = new javax.swing.JLabel();
        amountOfPeopleResult = new javax.swing.JLabel();
        amountOfCuadrantsResult = new javax.swing.JLabel();
        amountOfObjectsResult = new javax.swing.JLabel();
        amountOfBoxesResult = new javax.swing.JLabel();
        amountObjectsPanel = new javax.swing.JPanel();
        amountCeramicObjetsT = new javax.swing.JLabel();
        amountLithicObjectsT = new javax.swing.JLabel();
        ceramicObjectsResult = new javax.swing.JLabel();
        lithicObjectsResult = new javax.swing.JLabel();
        statisticsPanel = new javax.swing.JPanel();
        titleStatistics = new javax.swing.JLabel();
        averageWeighT = new javax.swing.JLabel();
        maxWeighT = new javax.swing.JLabel();
        minWeighT = new javax.swing.JLabel();
        averageResult = new javax.swing.JLabel();
        maxResult = new javax.swing.JLabel();
        minResult = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BackToMenuButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        dbaddedPanel.setBackground(new java.awt.Color(255, 255, 255));

        amountOfPeopleT.setText("Cantidad de Personas:");

        amountOfCuadrantT.setText("Cantidad de Cuadriculas:");

        amountOfObjectsT.setText("Cantidad de Objetos:");

        amountOfBoxesT.setText("Cantidad de Cajas:");

        amountOfPeopleResult.setText("jLabel5");

        amountOfCuadrantsResult.setText("jLabel6");

        amountOfObjectsResult.setText("jLabel7");

        amountOfBoxesResult.setText("jLabel8");

        javax.swing.GroupLayout dbaddedPanelLayout = new javax.swing.GroupLayout(dbaddedPanel);
        dbaddedPanel.setLayout(dbaddedPanelLayout);
        dbaddedPanelLayout.setHorizontalGroup(
            dbaddedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbaddedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dbaddedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amountOfPeopleT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amountOfCuadrantT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amountOfObjectsT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amountOfBoxesT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dbaddedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dbaddedPanelLayout.createSequentialGroup()
                        .addGroup(dbaddedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amountOfPeopleResult, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountOfCuadrantsResult, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountOfBoxesResult, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(614, Short.MAX_VALUE))
                    .addGroup(dbaddedPanelLayout.createSequentialGroup()
                        .addComponent(amountOfObjectsResult, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        dbaddedPanelLayout.setVerticalGroup(
            dbaddedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbaddedPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(dbaddedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountOfPeopleT)
                    .addComponent(amountOfPeopleResult))
                .addGap(18, 18, 18)
                .addGroup(dbaddedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountOfCuadrantT)
                    .addComponent(amountOfCuadrantsResult))
                .addGap(18, 18, 18)
                .addGroup(dbaddedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountOfObjectsT)
                    .addComponent(amountOfObjectsResult))
                .addGap(22, 22, 22)
                .addGroup(dbaddedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountOfBoxesT)
                    .addComponent(amountOfBoxesResult))
                .addContainerGap(379, Short.MAX_VALUE))
        );

        jPanel1.add(dbaddedPanel, "card4");

        amountObjectsPanel.setBackground(new java.awt.Color(255, 255, 255));

        amountCeramicObjetsT.setText("Cantidad de Objetos Ceramicos:");

        amountLithicObjectsT.setText("Cantidad de Objetos Liticos:");

        ceramicObjectsResult.setText("jLabel2");

        lithicObjectsResult.setText("jLabel3");

        javax.swing.GroupLayout amountObjectsPanelLayout = new javax.swing.GroupLayout(amountObjectsPanel);
        amountObjectsPanel.setLayout(amountObjectsPanelLayout);
        amountObjectsPanelLayout.setHorizontalGroup(
            amountObjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amountObjectsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(amountObjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amountCeramicObjetsT, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(amountLithicObjectsT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(amountObjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ceramicObjectsResult, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lithicObjectsResult, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        amountObjectsPanelLayout.setVerticalGroup(
            amountObjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amountObjectsPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(amountObjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountCeramicObjetsT)
                    .addComponent(ceramicObjectsResult))
                .addGap(28, 28, 28)
                .addGroup(amountObjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLithicObjectsT)
                    .addComponent(lithicObjectsResult))
                .addContainerGap(429, Short.MAX_VALUE))
        );

        jPanel1.add(amountObjectsPanel, "card3");

        statisticsPanel.setBackground(new java.awt.Color(255, 255, 255));

        titleStatistics.setText("Estadisticas de los objetos");

        averageWeighT.setText("Peso promedio:");

        maxWeighT.setText("Peso Maximo:");

        minWeighT.setText("Peso Minimo:");

        averageResult.setText("jLabel1");

        maxResult.setText("jLabel2");

        minResult.setText("jLabel3");

        javax.swing.GroupLayout statisticsPanelLayout = new javax.swing.GroupLayout(statisticsPanel);
        statisticsPanel.setLayout(statisticsPanelLayout);
        statisticsPanelLayout.setHorizontalGroup(
            statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsPanelLayout.createSequentialGroup()
                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statisticsPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(titleStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statisticsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(minWeighT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maxWeighT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(averageWeighT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(averageResult, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxResult, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minResult, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statisticsPanelLayout.setVerticalGroup(
            statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleStatistics)
                .addGap(28, 28, 28)
                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(averageWeighT)
                    .addComponent(averageResult))
                .addGap(38, 38, 38)
                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxWeighT)
                    .addComponent(maxResult))
                .addGap(37, 37, 37)
                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minWeighT)
                    .addComponent(minResult))
                .addContainerGap(356, Short.MAX_VALUE))
        );

        jPanel1.add(statisticsPanel, "card2");

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));

        BackToMenuButton3.setText("Volver al Menu");
        BackToMenuButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackToMenuButton3MousePressed(evt);
            }
        });
        BackToMenuButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackToMenuButton3)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(BackToMenuButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToMenuButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackToMenuButton3ActionPerformed

    private void BackToMenuButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackToMenuButton3MousePressed
        this.guihandler.changeFrame(GUIHandler.menu);
    }//GEN-LAST:event_BackToMenuButton3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArithmeticDisplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArithmeticDisplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArithmeticDisplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArithmeticDisplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArithmeticDisplayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMenuButton3;
    private javax.swing.JLabel amountCeramicObjetsT;
    private javax.swing.JLabel amountLithicObjectsT;
    private javax.swing.JPanel amountObjectsPanel;
    private javax.swing.JLabel amountOfBoxesResult;
    private javax.swing.JLabel amountOfBoxesT;
    private javax.swing.JLabel amountOfCuadrantT;
    private javax.swing.JLabel amountOfCuadrantsResult;
    private javax.swing.JLabel amountOfObjectsResult;
    private javax.swing.JLabel amountOfObjectsT;
    private javax.swing.JLabel amountOfPeopleResult;
    private javax.swing.JLabel amountOfPeopleT;
    private javax.swing.JLabel averageResult;
    private javax.swing.JLabel averageWeighT;
    private javax.swing.JLabel ceramicObjectsResult;
    private javax.swing.JPanel dbaddedPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lithicObjectsResult;
    private javax.swing.JLabel maxResult;
    private javax.swing.JLabel maxWeighT;
    private javax.swing.JLabel minResult;
    private javax.swing.JLabel minWeighT;
    private javax.swing.JPanel statisticsPanel;
    private javax.swing.JLabel titleStatistics;
    // End of variables declaration//GEN-END:variables
}
