/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiComponents;

import Utils.ArithmeticResultGenerator.DBSRG;
import Utils.EntityHandlers.BoxHandler;
import Utils.GUIHandler;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author joako
 */
public class BoxDeleter extends javax.swing.JFrame {
    private BoxHandler boxhandler;
    private GUIHandler guihandler;
    
    /**
     * Creates new form BoxDeleater
     */
    public BoxDeleter(GUIHandler guiHandler) {
        initComponents();
        this.guihandler=guiHandler;
        this.boxhandler= new BoxHandler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deleaterTitle = new javax.swing.JLabel();
        codDeleater = new javax.swing.JTextField();
        confirmBotton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        backToMenuBotton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        deleaterTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleaterTitle.setText("Ingrese el codigo de la caja que desea eliminar:");

        codDeleater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codDeleaterActionPerformed(evt);
            }
        });

        confirmBotton.setText("Confirmar");
        confirmBotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmBottonMousePressed(evt);
            }
        });
        confirmBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleaterTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codDeleater))
                .addGap(18, 18, 18)
                .addComponent(confirmBotton)
                .addContainerGap(386, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(deleaterTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codDeleater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmBotton))
                .addContainerGap(485, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));

        backToMenuBotton.setText("Volver al menu");
        backToMenuBotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backToMenuBottonMousePressed(evt);
            }
        });
        backToMenuBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToMenuBotton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(backToMenuBotton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codDeleaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codDeleaterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codDeleaterActionPerformed

    private void confirmBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBottonActionPerformed
        
    }//GEN-LAST:event_confirmBottonActionPerformed

    private void confirmBottonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmBottonMousePressed
        String cod = codDeleater.getText();
        JFrame jFrame = new JFrame();
        try{
        int a = boxhandler.deleteBox(cod);
        if(a == -3){
            JOptionPane.showMessageDialog(jFrame, "La caja contiene objecto/s por lo cual no puede ser eliminada.");
        }else{
            JOptionPane.showMessageDialog(jFrame, "Elminacion realizada correctamente.");
        }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(jFrame, "Ocurrio un error al intentar borrar una caja..");
            System.out.println("fallo" +e.getMessage());
        }
    }//GEN-LAST:event_confirmBottonMousePressed

    private void backToMenuBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuBottonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_backToMenuBottonActionPerformed

    private void backToMenuBottonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMenuBottonMousePressed
        this.guihandler.changeFrame(GUIHandler.menu);
    }//GEN-LAST:event_backToMenuBottonMousePressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenuBotton;
    private javax.swing.JTextField codDeleater;
    private javax.swing.JButton confirmBotton;
    private javax.swing.JLabel deleaterTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
